# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\WORK\Courses\Aquaphoton\Mega Project\SODGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1113, 539)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.browse = QtWidgets.QPushButton(self.centralwidget)
        self.browse.setObjectName("browse")
        self.verticalLayout.addWidget(self.browse)
        self.path = QtWidgets.QLineEdit(self.centralwidget)
        self.path.setObjectName("path")
        self.verticalLayout.addWidget(self.path)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.im1 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.im1.setFont(font)
        self.im1.setAlignment(QtCore.Qt.AlignCenter)
        self.im1.setObjectName("im1")
        self.horizontalLayout.addWidget(self.im1)
        self.im2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.im2.setFont(font)
        self.im2.setAlignment(QtCore.Qt.AlignCenter)
        self.im2.setObjectName("im2")
        self.horizontalLayout.addWidget(self.im2)
        self.im3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.im3.setFont(font)
        self.im3.setAlignment(QtCore.Qt.AlignCenter)
        self.im3.setObjectName("im3")
        self.horizontalLayout.addWidget(self.im3)
        self.im4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.im4.setFont(font)
        self.im4.setAlignment(QtCore.Qt.AlignCenter)
        self.im4.setObjectName("im4")
        self.horizontalLayout.addWidget(self.im4)
        self.im5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.im5.setFont(font)
        self.im5.setAlignment(QtCore.Qt.AlignCenter)
        self.im5.setObjectName("im5")
        self.horizontalLayout.addWidget(self.im5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.enter = QtWidgets.QPushButton(self.centralwidget)
        self.enter.setObjectName("enter")
        self.verticalLayout_2.addWidget(self.enter)
        self.output = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.output.setFont(font)
        self.output.setAlignment(QtCore.Qt.AlignCenter)
        self.output.setObjectName("output")
        self.verticalLayout_2.addWidget(self.output)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.browse.setText(_translate("MainWindow", "Browse"))
        self.im1.setText(_translate("MainWindow", "image1"))
        self.im2.setText(_translate("MainWindow", "image2"))
        self.im3.setText(_translate("MainWindow", "image3"))
        self.im4.setText(_translate("MainWindow", "image4"))
        self.im5.setText(_translate("MainWindow", "image5"))
        self.enter.setText(_translate("MainWindow", "Detect"))



        
        self.output.setText(_translate("MainWindow", "Final Image will appear here"))
